# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_height', models.CharField(max_length=10)),
                ('person_weight', models.CharField(max_length=10)),
                ('person_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service1.Person')),
            ],
        ),
    ]
