# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service1', '0003_auto_20180805_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persondetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=11)),
                ('person_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service1.Person')),
            ],
        ),
    ]
